;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	cider-load-buffer
	end-of-buffer
	haml-electric-backspace
	ido-find-file
	indent-for-tab-command
	org-delete-char
	org-kill-line
	org-self-insert-command
	org-yank
	paredit-RET
	paredit-backslash
	paredit-delete-char
	paredit-doublequote
	paredit-forward-delete
	paredit-kill
	paredit-open-curly
	paredit-open-round
	paredit-open-square
	paredit-raise-sexp
	paredit-semicolon
	swiper
	xterm-paste
	yaml-electric-backspace
	yaml-electric-dash-and-dot
	))

(setq mc/cmds-to-run-once
      '(
	suspend-frame
	))
