;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cider-load-buffer
        cljr-raise-sexp
        cljr-slash
        indent-for-tab-command
        overwrite-mode
        paredit-backslash
        paredit-close-curly
        paredit-doublequote
        paredit-forward-delete
        paredit-forward-slurp-sexp
        paredit-kill
        paredit-open-curly
        paredit-open-round
        paredit-open-square
        paredit-semicolon
        paxedit-backward-kill
        paxedit-forward-kill
        sgml-slash
        suspend-frame
        tagedit-insert-equal
        ))

(setq mc/cmds-to-run-once
      '(
        haml-electric-backspace
        org-self-insert-command
        ))
